### ISSUE TITLE
Security Contact Needed

### ISSUE THREAD

**Issue by agustingianni** [gsf/whiskers.js#33]
Hello,

I am a member of the GitHub Security Lab (https://securitylab.github.com).

I've attempted to reach a maintainer for this project to report a potential security issue but have been unable to verify the report was received. Please could a project maintainer contact us at securitylab@github.com, or provide an email address so we can contact you.

Thank you,
Agustin Gianni (@agustingianni)
GitHub Security Lab

**Comment by fogfish** [comment]
@gsf Sean, will you handle this or I can jump into it?

**Comment by fogfish** [comment]
@agustingianni Please feel free to contact me on this issue. My email is available at the profile.

**Comment by agustingianni** [comment]
Thank you @fogfish I will drop you an email then. Thanks.

**Comment by agustingianni** [comment]
@fogfish uhm I just checked your profile but I don't see your email. Maybe it is marked as private?

**Comment by fogfish** [comment]
@agustingianni yeah, it might be private. I've sent the email to the address accordingly your instructions. 

Have a great day!
